kind: pipeline
name: dev

steps:
- name: build
  image: node
  commands: 
  - npm config set registry https://registry.npm.taobao.org
  - npm install
  - npm run build

- name: build-image
  image: plugins/docker
  settings:
    repo: jackyzhangjh/drone-ci-demo
    auto_tag: true